// Generated by gencpp from file dynamixel_sdk_examples/GetVelocityResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETVELOCITYRESPONSE_H
#define DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamixel_sdk_examples
{
template <class ContainerAllocator>
struct GetVelocityResponse_
{
  typedef GetVelocityResponse_<ContainerAllocator> Type;

  GetVelocityResponse_()
    : velocity(0)  {
    }
  GetVelocityResponse_(const ContainerAllocator& _alloc)
    : velocity(0)  {
  (void)_alloc;
    }



   typedef int32_t _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetVelocityResponse_

typedef ::dynamixel_sdk_examples::GetVelocityResponse_<std::allocator<void> > GetVelocityResponse;

typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetVelocityResponse > GetVelocityResponsePtr;
typedef boost::shared_ptr< ::dynamixel_sdk_examples::GetVelocityResponse const> GetVelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator1> & lhs, const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamixel_sdk_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1221446a6cb55fc620353cce70eed4a";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1221446a6cb55fcULL;
  static const uint64_t static_value2 = 0x620353cce70eed4aULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamixel_sdk_examples/GetVelocityResponse";
  }

  static const char* value(const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 velocity\n"
"\n"
;
  }

  static const char* value(const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetVelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamixel_sdk_examples::GetVelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIXEL_SDK_EXAMPLES_MESSAGE_GETVELOCITYRESPONSE_H
