# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from qwt.text import QwtTextLabel
import os, signal


class Ui_Form(object):
    def launchFile(self):
        #Check radio button state
        controllerMode=self.control_mode_radio.isChecked()

        if(self.launchP.processId()!=0):
            os.kill(self.launchP.processId(), signal.SIGINT)
            self.launchP.waitForFinished(-1)

        if(self.simulation_radio.isChecked()):
            self.launchP.start("ros2", ["launch", "mobile_robot", "simulation.launch.py"])
        else:
            self.launchP.start("ros2", ["launch", "mobile_robot", "real_world.launch.py"])
        self.umSlider.setEnabled(not controllerMode)
        self.b1d_slider.setEnabled(not controllerMode)
        self.b2d_slider.setEnabled(not controllerMode)
        self.reset_button.setEnabled(not controllerMode)
        #print("Process id: ", self.launchP.processId())
        self.simulation_radio.setDisabled(True)
        self.real_world_radio.setDisabled(True)
        self.launch_button.setDisabled(True)
        self.control_mode_radio.setDisabled(True)
        self.manual_mode_radio.setDisabled(True)
        return
    
    def endLaunch(self):
        # print("Estado: ", self.launchP.state())
        if(self.launchP.processId()!=0):
            # print("Trying to terminate the process ", self.launchP.processId())
            os.kill(self.launchP.processId(), signal.SIGINT)
            self.launchP.waitForFinished(-1)
        self.simulation_radio.setDisabled(False)
        self.real_world_radio.setDisabled(False)
        self.launch_button.setDisabled(False)
        self.end_button.setDisabled(True)
        self.control_mode_radio.setEnabled(True)
        self.manual_mode_radio.setEnabled(True)
        # self.umSlider.setDisabled(True)
        # self.b1d_slider.setDisabled(True)
        # self.b2d_slider.setDisabled(True)
        return
    
    def exit(self):
        print("Estado: ", self.launchP.state())
        if(self.launchP.processId()!=0):
            print("Trying to terminate the process ", self.launchP.processId())
            os.kill(self.launchP.processId(), signal.SIGINT)
            self.launchP.waitForFinished(-1)
        Form.close()
        return
    def resetSliders(self):
        self.umSlider.setProperty("value", 0)
        self.b1d_slider.setProperty("value", 0)
        self.b2d_slider.setProperty("value", 0)
        return
        
    def setupUi(self, Form):
        self.launchP=QtCore.QProcess()
        Form.setObjectName("Form")
        Form.resize(419, 384)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 401, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.manual_mode_radio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.manual_mode_radio.setObjectName("manual_mode_radio")
        self.ControlModeGroup = QtWidgets.QButtonGroup(Form)
        self.ControlModeGroup.setObjectName("ControlModeGroup")
        self.ControlModeGroup.addButton(self.manual_mode_radio)
        self.gridLayout.addWidget(self.manual_mode_radio, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Runtime = QwtTextLabel(self.gridLayoutWidget)
        self.Runtime.setEnabled(False)
        self.Runtime.setObjectName("Runtime")
        self.horizontalLayout.addWidget(self.Runtime)
        self.simulation_radio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.simulation_radio.setEnabled(False)
        self.simulation_radio.setCheckable(True)
        self.simulation_radio.setChecked(False)
        self.simulation_radio.setObjectName("simulation_radio")
        self.RuntimeGroup = QtWidgets.QButtonGroup(Form)
        self.RuntimeGroup.setObjectName("RuntimeGroup")
        self.RuntimeGroup.addButton(self.simulation_radio)
        self.horizontalLayout.addWidget(self.simulation_radio)
        self.real_world_radio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.real_world_radio.setEnabled(False)
        self.real_world_radio.setObjectName("real_world_radio")
        self.RuntimeGroup.addButton(self.real_world_radio)
        self.horizontalLayout.addWidget(self.real_world_radio)
        self.gridLayout.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 8, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TextLabel = QwtTextLabel(self.gridLayoutWidget)
        self.TextLabel.setObjectName("TextLabel")
        self.verticalLayout.addWidget(self.TextLabel)
        self.umSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.umSlider.setEnabled(False)
        self.umSlider.setMinimum(-100)
        self.umSlider.setMaximum(100)
        self.umSlider.setProperty("value", 0)
        self.umSlider.setOrientation(QtCore.Qt.Horizontal)
        self.umSlider.setObjectName("umSlider")
        self.verticalLayout.addWidget(self.umSlider)
        self.beta1dot = QwtTextLabel(self.gridLayoutWidget)
        self.beta1dot.setObjectName("beta1dot")
        self.verticalLayout.addWidget(self.beta1dot)
        self.b1d_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.b1d_slider.setEnabled(False)
        self.b1d_slider.setMinimum(-50)
        self.b1d_slider.setMaximum(50)
        self.b1d_slider.setPageStep(10)
        self.b1d_slider.setProperty("value", 0)
        self.b1d_slider.setOrientation(QtCore.Qt.Horizontal)
        self.b1d_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.b1d_slider.setObjectName("b1d_slider")
        self.verticalLayout.addWidget(self.b1d_slider)
        self.beta2dot = QwtTextLabel(self.gridLayoutWidget)
        self.beta2dot.setObjectName("beta2dot")
        self.verticalLayout.addWidget(self.beta2dot)
        self.b2d_slider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.b2d_slider.setEnabled(False)
        self.b2d_slider.setMinimum(-50)
        self.b2d_slider.setMaximum(50)
        self.b2d_slider.setSliderPosition(0)
        self.b2d_slider.setOrientation(QtCore.Qt.Horizontal)
        self.b2d_slider.setObjectName("b2d_slider")
        self.verticalLayout.addWidget(self.b2d_slider)
        self.gridLayout.addLayout(self.verticalLayout, 6, 0, 1, 1)
        self.reset_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.reset_button.setEnabled(False)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout.addWidget(self.reset_button, 7, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 1)
        self.control_mode_radio = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.control_mode_radio.setCheckable(True)
        self.control_mode_radio.setChecked(False)
        self.control_mode_radio.setObjectName("control_mode_radio")
        self.ControlModeGroup.addButton(self.control_mode_radio)
        self.gridLayout.addWidget(self.control_mode_radio, 1, 0, 1, 1)
        self.launch_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.launch_button.setEnabled(False)
        self.launch_button.setObjectName("launch_button")
        self.gridLayout.addWidget(self.launch_button, 10, 0, 1, 1)
        self.end_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.end_button.setEnabled(False)
        self.end_button.setObjectName("end_button")
        self.gridLayout.addWidget(self.end_button, 11, 0, 1, 1)
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(320, 340, 89, 25))
        self.close_button.setObjectName("close_button")

        self.retranslateUi(Form)
        self.control_mode_radio.clicked['bool'].connect(self.simulation_radio.setEnabled)
        self.control_mode_radio.clicked['bool'].connect(self.real_world_radio.setEnabled)
        self.control_mode_radio.clicked['bool'].connect(self.umSlider.setDisabled)
        self.control_mode_radio.clicked['bool'].connect(self.b1d_slider.setDisabled)
        self.control_mode_radio.clicked['bool'].connect(self.b2d_slider.setDisabled)
        self.control_mode_radio.clicked['bool'].connect(self.reset_button.setDisabled)
        self.manual_mode_radio.clicked['bool'].connect(self.simulation_radio.setEnabled)
        self.manual_mode_radio.clicked['bool'].connect(self.umSlider.setEnabled)
        self.manual_mode_radio.clicked['bool'].connect(self.b1d_slider.setEnabled)
        self.manual_mode_radio.clicked['bool'].connect(self.b2d_slider.setEnabled)
        self.manual_mode_radio.clicked['bool'].connect(self.reset_button.setEnabled)
        self.manual_mode_radio.clicked['bool'].connect(self.real_world_radio.setEnabled)
        self.simulation_radio.clicked['bool'].connect(self.launch_button.setEnabled)
        self.real_world_radio.clicked['bool'].connect(self.launch_button.setEnabled)
        self.launch_button.clicked['bool'].connect(self.simulation_radio.setDisabled)
        self.launch_button.clicked['bool'].connect(self.real_world_radio.setDisabled)
        self.launch_button.clicked['bool'].connect(self.end_button.setDisabled)
        self.launch_button.clicked['bool'].connect(self.launchFile)
        self.reset_button.clicked['bool'].connect(self.resetSliders)
        self.end_button.clicked['bool'].connect(self.endLaunch)
        self.close_button.clicked['bool'].connect(self.exit)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.control_mode_radio, self.simulation_radio)
        Form.setTabOrder(self.simulation_radio, self.real_world_radio)
        Form.setTabOrder(self.real_world_radio, self.manual_mode_radio)
        Form.setTabOrder(self.manual_mode_radio, self.umSlider)
        Form.setTabOrder(self.umSlider, self.b1d_slider)
        Form.setTabOrder(self.b1d_slider, self.close_button)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.manual_mode_radio.setText(_translate("Form", "Manual mode"))
        self.Runtime.setPlainText(_translate("Form", "Runtime"))
        self.simulation_radio.setText(_translate("Form", "Simulation"))
        self.real_world_radio.setText(_translate("Form", "Real world"))
        self.TextLabel.setPlainText(_translate("Form", "Um control input"))
        self.beta1dot.setPlainText(_translate("Form", "Beta dot 1"))
        self.beta2dot.setPlainText(_translate("Form", "Beta 2 dot"))
        self.reset_button.setText(_translate("Form", "Reset sliders"))
        self.control_mode_radio.setText(_translate("Form", "Controller mode"))
        self.launch_button.setText(_translate("Form", "Launch"))
        self.end_button.setText(_translate("Form", "End"))
        self.close_button.setText(_translate("Form", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
